### ISSUE TITLE
Albums with multiple artists

### ISSUE THREAD

**Issue by LukaszH77** [nate-xyz/resonance#10]
Resonance should treat a multi-artist album as one, not split it into several albums. 
![Zrzut ekranu z 2023-04-05 09-11-43](https://user-images.githubusercontent.com/121253127/230009718-8171ff12-029c-4e78-961b-f5f00b042433.png)

**Comment by nate-xyz** [comment]
I think this is a question of album artist tags vs artist tags. An album shouldn't split if the album artist tag is the same. (Resonance groups albums based on album name + album artist tag, see [here](https://github.com/nate-xyz/resonance/blob/3875a2424743b70a8ccf4eb6e383151daa9a71b3/src/importer.rs#LL335C73-L335C73)) Artist tags are allowed to be different per track. Can you post what your album artist tags are for your albums?

**Comment by LukaszH77** [comment]
They are empty.

**Comment by nate-xyz** [comment]
Let me know if it groups properly if you add album artist tags

**Comment by LukaszH77** [comment]
Yep, it works like a charm. Thank you for your help. And for this amazing looking app!
