### ISSUE TITLE
[Crash] Manualy remove the last track from queue

### ISSUE THREAD

**Issue by Sky-NiniKo** [nate-xyz/resonance#11]
## How to reproduce
1. Play a track
2. Go to "Queue" tab
3. Click on "Toggle Playlist Sidebar"
4. Click on "Edit Queue"
5. "Remove Track From Queue" (red button) until there is no more track in the queue
6. Resonance crashes

## Video (flickering due to recording)
[Exemple.webm](https://user-images.githubusercontent.com/61370893/230269326-e4b99c17-260b-4e6c-be26-9ebc3b318062.webm)

## Traceback
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/player/queue.rs:107:21 stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/commit/30cbab97c4e337df5de5f56ffa8528993b4adf65
