### ISSUE TITLE
Album covers are broken on hover

### ISSUE THREAD

**Issue by bertob** [nate-xyz/resonance#14]
When hovering an album on the grid, it's just white:

![image](https://user-images.githubusercontent.com/1908896/230500041-5f431a6c-b3c9-4d3e-a7ff-a1c79f715747.png)

**Comment by nate-xyz** [comment]
Does this happen in dark mode?

**Comment by bertob** [comment]
No, looks like it works fine in dark (covers get slightly lighter on hover).

**Comment by nate-xyz** [comment]
Ok, a lot of the issues with visibility you raised (https://github.com/nate-xyz/resonance/issues/16, https://github.com/nate-xyz/resonance/issues/15) are because the app is meant to be in dark mode, so I'll make it dark mode by default.

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/commit/901e76f87787c194ef31a9252cee8048f9041510
