### ISSUE TITLE
Fallback album cover papercuts

### ISSUE THREAD

**Issue by bertob** [nate-xyz/resonance#15]
The cover art fallback has a number of issues currently:
- The dark-on-dark text is hard to read, I'd reduce the opacity
- The light font weight should not be used at non-huge sizes, and this is definitely too small. I'd just use the regular font weight.
- When the text reflows, it's left-aligned, which looks super weird above a centered artist name, I'd always center it
- There's no horizontal padding on the text, so it goes too close to the edges, I'd add 12px padding

![image](https://user-images.githubusercontent.com/1908896/230500252-1f62217d-4bc4-40da-83bc-5fc51ad6273d.png)

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/issues/14#issuecomment-1500246350

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/commit/ebf673f8598cc5a2b6e3816832b4853c2231c202
