### ISSUE TITLE
Preferences: List rows look broken

### ISSUE THREAD

**Issue by bertob** [nate-xyz/resonance#16]
The lists on the preferences window look very strange with the black-on-gray, white separators, etc. I'd either recolor the whole window (including headerbar etc.) and make them semi-transparent, or just keep the default styling for background, listbox, and everything else.

![image](https://user-images.githubusercontent.com/1908896/230503547-edc8e1b5-8cb0-4c43-a3ed-9c5a663877d0.png)

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/issues/14#issuecomment-1500246350
