### ISSUE TITLE
Use album's cover art for tracks if the track doesn't have an embedded one

### ISSUE THREAD

**Issue by Protrikk** [nate-xyz/resonance#2]
Picture showing the visible issue :-)
![obraz](https://user-images.githubusercontent.com/42098407/229244111-127ba25f-d1fb-40d1-a451-60b7146cecca.png)

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/commit/8c313b2198829ad794e3f9ba72ff19aa1b6c48c7
