### ISSUE TITLE
Add to AUR

### ISSUE THREAD

**Issue by Movisivi** [nate-xyz/resonance#23]
I'm a bit dumb on how to build this.  Don't like flatpak, would prefer aur version to update with rest of packages

**Comment by 3laws** [comment]
@Movisivi I'm here actually to read the documentation, if any, to make a PKGBUILD, will just test building from source to test it. Will update accordingly and maybe add a MR to add it as an option. Don't quote me on this since I was barely getting used to RPM documentation and I've never built a PKGBUILD before.

May as well build an RPM while at it.

**Comment by Movisivi** [comment]
I could make the PKGBUILD for you if I knew how to build this from source xD

**Comment by 3laws** [comment]
Ran it via 

`meson build`

then

`ninja -C build install`

Having some UI inconsistencies but so far nothing is broken, nor anything out of the already reported bugs in here.

I'll be looking forward for your build.

**Comment by nate-xyz** [comment]
@yochananmarqos

**Comment by Movisivi** [comment]
I got it to build but it just stays "loading" my library. I only have 1000 songs and its been running for 30 minutes. Screw it, I'll just keep using Tauon.

**Comment by nate-xyz** [comment]
> I got it to build but it just stays "loading" my library. I only have 1000 songs and its been running for 30 minutes. Screw it, I'll just keep using Tauon.

You realize this is really early software and I just released it right? I won't be able to improve it without feedback. Do you mind posting the debug logs from the import process? Is it hanging on one particular track?

**Comment by nate-xyz** [comment]
> I got it to build but it just stays "loading" my library. I only have 1000 songs and its been running for 30 minutes. Screw it, I'll just keep using Tauon.

Did you have the pip dependencies installed? My fault for not having them in the readme, realized after https://github.com/nate-xyz/resonance/issues/35

**Comment by yochananmarqos** [comment]
@nate-xyz Sorry, I'm not adding much of anything new to the AUR right now. I'm actually in the process of doing some Spring Cleaning and dropping some old AUR packages. It doesn't help that my health isn't the best right now.

**Comment by nate-xyz** [comment]
@yochananmarqos No worries! Hope you feel better soon!

**Comment by Movisivi** [comment]
> > I got it to build but it just stays "loading" my library. I only have 1000 songs and its been running for 30 minutes. Screw it, I'll just keep using Tauon.
> 
> Did you have the pip dependencies installed? My fault for not having them in the readme, realized after #35

Ah that was it I think. I haven't re-ran build yet but only mutagen was installed on my system.

**Comment by 3laws** [comment]
@Movisivi the package has been submitted to the [AUR](https://aur.archlinux.org/packages/resonance).

You can verify my PR @nate-xyz
