### ISSUE TITLE
Font 

### ISSUE THREAD

**Issue by Bananaman** [nate-xyz/resonance#26]
Hi, I would consider this low-priority, but I'm curious: Would it be possible to make the UI fonts configurable? What are they coming from right now?

I think it would be really cool to be able to set the fonts, but perhaps I am alone in thinking this. If so, feel free to close this. :)

**Comment by nate-xyz** [comment]
I think this is probably out of scope for the app. I think they're just set by the system?

**Comment by Bananaman** [comment]
> I think they're just set by the system?

Ahh, I dunno, I was trying to figure it out and didn't see any references to fonts in the codebase so it might be something like that. :) Feel free to close this. I have no idea how to use this UI toolkit.

**Comment by tfuxu** [comment]
You can use GNOME Tweaks to change fonts in GTK apps:
![Screenshot from 2023-04-08 01-56-38](https://user-images.githubusercontent.com/73042332/230693908-ab259556-8917-4a0b-84d4-1f302618639a.png)

**Comment by Bananaman** [comment]
@tfuxu Oh hey that actually works! Turns out the app uses the "Interface Font" for everything! :)
