### ISSUE TITLE
MPRIS restarts the song when you press pause and play back

### ISSUE THREAD

**Issue by Nekothegamer** [nate-xyz/resonance#33]
when pressing pause while a song is playing and then pressing play again restarts the song

https://user-images.githubusercontent.com/112352776/230730733-4a0f7bbe-93ca-4c9d-9a37-80b49d724601.mp4

**Comment by nate-xyz** [comment]
duplicate of https://github.com/nate-xyz/resonance/issues/19

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/commit/3d24b655eab853dad9f40150ed03efc6aa12beee
