### ISSUE TITLE
[Enhancement] mention python deps in Readme

### ISSUE THREAD

**Issue by werdahias** [nate-xyz/resonance#35]
OS: Debian testing
rustc 1.65

I built the latest source from master. On startup, two bugs occurred:

1) the window kinda snaps to to the topleft corner
2) the initial import hangs on importing tags unless you install python3-tqdm, python3-loguru and python3-mutagen

imho it'd make sense to mention this in the docs,

**Comment by soumyaDghosh** [comment]
How about a snap? Working fine, just like the flatpak? would you like it? @nate-xyz
