### ISSUE TITLE
Distinguish header from scrollview

### ISSUE THREAD

**Issue by bertob** [nate-xyz/resonance#5]
The content currently scrolls into nothingness, I'd apply the same gradient to the headerbar that's being used for the bottom playback bar.

![image](https://user-images.githubusercontent.com/1908896/229611622-6401fd84-096c-4372-9ecd-bcc3af7b3eee.png)

**Comment by nate-xyz** [comment]
I see your point and I agree it's not ideal, but I would like to preserve the aesthetic of the combined window header bar and content. If I apply the control bar css to the header it will visually break it up. I'm not really sure what a good solution is. One idea I had was to add the header as an overlay on top of the content and blur the background of the header bar, but unfortunately backdrop-filter isn't implemented in gtk css: https://gitlab.gnome.org/GNOME/gtk/-/issues/3231

**Comment by bertob** [comment]
What you could do is an undershoot border or shadow that are only visible when it's actually scrolled, but then I'd use it for the bottom bar as well.

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/commit/839afb0d40fd5e22299d25aa17f97dda3dc23eca
