### ISSUE TITLE
Add an option for shuffling the entire library

### ISSUE THREAD

**Issue by JesusXD88** [nate-xyz/resonance#57]
It would be a great idea to have an option to click a button and all the songs of the library would be added to the queue, and shuffled together, like some other media players do. Or just an option that added all songs in library to the queue and that you could shuffle with the already built-in shuffle option (like on Rhythmbox). It's mostly the only thing I miss in Resonance, everything else is very neat👍.

**Comment by nate-xyz** [comment]
Where do you think this option / button should go?

**Comment by JesusXD88** [comment]
Maybe on this side a button saying like "Shuffle entire library"?
![Captura desde 2023-04-10 19-23-10](https://user-images.githubusercontent.com/71974251/230957046-f24bb1fa-4b01-40d8-aaf5-ae1ddf759d2e.png)

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/commit/147cb3986d66a102c61f7cc9be9a288b9aeba74c

**Comment by jasonhoblack** [comment]
@nate-xyz hi , i wanted to ask if the option was made into a player or not yet ? cant find it anywhere 

thx
