### ISSUE TITLE
Play album-from-track as default when playing track

### ISSUE THREAD

**Issue by legacychimera247** [nate-xyz/resonance#76]
well most of the times i click on a song to play it then leave the rest to play, but i noticed on here only the clicked song will be played, unless i selected the entire album on the cover

that's not what i would expect, but considering this may be intentional, maybe having this selectable?

**Comment by legacychimera247** [comment]
yeah, like i play directly song n.2 from a record, then reasonance subsequently plays song n.3, n.4 and so on till the end of the album (or even till the end of the list, as preference set)

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/commit/6fa91faf518a955da729d22fa2ad37d380ad9ba0
