### ISSUE TITLE
have albums in artist page sorted by date

### ISSUE THREAD

**Issue by legacychimera247** [nate-xyz/resonance#78]
i know you can choose albums to be sorted chronologically, but i need to do per artist and anyway, everytime i close the page i need to do it again

can it be made to be permanent?

**Comment by nate-xyz** [comment]
yeah it's in the settings

**Comment by legacychimera247** [comment]
if it's the "album detail default sort, it's already sorted per year, but does not work, as albums are still listed alphabetically

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/commit/d2c10b4f6e8f5bc1a697eb6f79aa06f32e692c75

**Comment by nate-xyz** [comment]
Thanks for catching this one!
