### ISSUE TITLE
Song resets when using playerctl play-pause

### ISSUE THREAD

**Issue by kaii-lb** [nate-xyz/resonance#87]
I use playerctl's play-pause feature to toggle music using the keyboard and waybar widget, but it seems to always reset the song when playing. So like the song could be halfway through (so like minute 1:40 for example), then i pause, resume and its back to the start (minute 0:00).

**Comment by nate-xyz** [comment]
what version are you using? This was solved in https://github.com/nate-xyz/resonance/issues/19

**Comment by kaii-lb** [comment]
oh shi- im on 1.2
didn't even notice. Sorry for the useless waste of time-
