### ISSUE TITLE
unable to display artists with special characters like &

### ISSUE THREAD

**Issue by legacychimera247** [nate-xyz/resonance#89]
well i guess the title says it all :) i just have an empty field till i click on it

`(resonance:2): Gtk-WARNING **: 02:59:04.082: Failed to set text '<span weight="book" size="medium">Courage My Love & Walt Flanagan</span>' from markup due to error parsing markup`

this is the terminal output for this error

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/commit/5d4cbfd6de31a6f1b3f6550a3bb4630502927f1d
